In [1]:
import pandas as pd
import numpy as np
import mibian
import math
from scipy.stats import norm
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [2]:
#Calls = pd.read_csv('nifty_311221_190122_1min_calls.csv')
Calls = pd.read_csv('nifty_311221_190122_1min_calls_py_vollib.csv')

### Training Model

In [23]:
def pre_train_process(df,startDate,windowLength,isNormalized,moneyness):
    tmp = df.copy()
    tmp = tmp[np.abs(tmp['delta'] - moneyness) <= 0.025]
    start = startDate
    train_start_index = tmp[tmp['date'] == start].index[0]
    train_window_length = windowLength
    train_end_index = train_start_index+train_window_length
    tmp = tmp.iloc[train_start_index:train_end_index]
    if(isNormalized==True):
    ## normalize the option price change and future price change
        tmp['opt_price_chg'] = tmp['opt_price'].diff()
        tmp['fut_price_chg'] = tmp['fut_price'].diff()
        tmp = tmp[tmp['fut_price_chg']!=0]
    else:
        tmp['opt_price_chg'] = tmp['opt_price'] / tmp['opt_price'].shift()
        tmp['fut_price_chg'] = tmp['fut_price'] / tmp['fut_price'].shift()
        tmp = tmp[tmp['fut_price_chg']!=1]
    tmp = tmp[['ts','opt_price_chg','fut_price_chg','delta','vega','days_to_expiry','fut_price']]
    tmp.reset_index(drop=True,inplace=True)
    train_set = pd.DataFrame()
    train_set['y'] = (tmp['opt_price_chg'] - tmp['delta']*tmp['fut_price_chg'])*np.sqrt(tmp['days_to_expiry'])/tmp['vega']*tmp['fut_price']/tmp['fut_price_chg']
    train_set['x1'] = tmp['delta']
    train_set['x2'] = tmp['delta']**2
    train_set.drop(index=0,inplace=True)
    return train_set

In [4]:
def train_model(train_set):
    x = sm.add_constant(train_set.iloc[:,1:])
    y = train_set['y']
    model = sm.OLS(y,x)
    result = model.fit()
    return result

In [5]:
def predict_MV_delta(df,startDate,windowLength,result):
    tmp = df.copy()
    test_start_index = tmp[tmp['date'] == startDate].index[0]
    test_window_length = windowLength
    test_end_index = test_start_index + test_window_length
    tmp = tmp.iloc[test_start_index:test_end_index]
    tmp = tmp[['ts','delta','vega','days_to_expiry','fut_price']]
    b0 = result.params[0]
    b1 = result.params[1]
    b2 = result.params[2]
    tmp['y_hat'] = b0+b1*tmp['delta']+b2*tmp['delta']**2
    tmp['MV_delta'] = tmp['delta']+tmp['vega']/tmp['fut_price']/np.sqrt(tmp['days_to_expiry'])*(b0+b1*tmp['delta']+b2*tmp['delta']**2)
    return tmp

### Read in data

## NOTE! when select df, I should just choose one contract to continue to do the research!!!

In [53]:
Calls = pd.read_csv('nifty_311221_190122_1min_calls_py_vollib.csv')
Calls['opt_symbol'].unique().size

79

In [54]:
Calls[Calls['opt_symbol']=='NIFTY22JAN17450CE']

,Unnamed: 0,date,opt_price,volume_x,opt_symbol,fut_price,volume_y,fut_symbol,name,expiry,strike,instrument_type,ts,days_to_expiry,IV,delta,vega
0,0,2021-12-31 09:15:00+05:30,231.50,0.0,NIFTY22JAN17450CE,17311.00,174100.0,NIFTY22JANFUT,NIFTY,2022-01-27 15:30:30,17450.0,CE,2021-12-31 09:15:00,27.260764,0.129723,0.434036,341.824831
59,107,2021-12-31 09:16:00+05:30,235.00,550.0,NIFTY22JAN17450CE,17332.10,191750.0,NIFTY22JANFUT,NIFTY,2022-01-27 15:30:30,17450.0,CE,2021-12-31 09:16:00,27.260069,0.127160,0.443862,342.803555
134,241,2021-12-31 09:17:00+05:30,237.85,5450.0,NIFTY22JAN17450CE,17330.70,83200.0,NIFTY22JANFUT,NIFTY,2022-01-27 15:30:30,17450.0,CE,2021-12-31 09:17:00,27.259375,0.128703,0.443975,342.324881
208,372,2021-12-31 09:18:00+05:30,237.65,200.0,NIFTY22JAN17450CE,17338.25,80850.0,NIFTY22JANFUT,NIFTY,2022-01-27 15:30:30,17450.0,CE,2021-12-31 09:18:00,27.258681,0.127123,0.447192,342.869310
268,484,2021-12-31 09:19:00+05:30,238.10,3050.0,NIFTY22JAN17450CE,17335.00,64800.0,NIFTY22JANFUT,NIFTY,2022-01-27 15:30:30,17450.0,CE,2021-12-31 09:19:00,27.257986,0.127968,0.445887,342.580852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320222,683091,2022-01-19 15:27:00+05:30,544.15,0.0,NIFTY22JAN17450CE,17974.25,64400.0,NIFTY22JANFUT,NIFTY,2022-01-27 15:30:30,17450.0,CE,2022-01-19 15:27:00,8.002431,0.130574,0.900388,195.858694
320243,683141,2022-01-19 15:28:00+05:30,544.15,0.0,NIFTY22JAN17450CE,17976.00,56600.0,NIFTY22JANFUT,NIFTY,2022-01-27 15:30:30,17450.0,CE,2022-01-19 15:28:00,8.001736,0.127700,0.905992,195.972441
320336,683357,2022-01-19 15:29:00+05:30,544.15,0.0,NIFTY22JAN17450CE,17975.50,38600.0,NIFTY22JANFUT,NIFTY,2022-01-27 15:30:30,17450.0,CE,2022-01-19 15:29:00,8.001042,0.128543,0.904365,195.928992
320372,683436,2022-01-19 15:30:00+05:30,544.15,0.0,NIFTY22JAN17450CE,17975.50,200.0,NIFTY22JANFUT,NIFTY,2022-01-27 15:30:30,17450.0,CE,2022-01-19 15:30:00,8.000347,0.128548,0.904365,195.920489
320424,683546,2022-01-19 16:19:00+05:30,544.15,0.0,NIFTY22JAN17450CE,17975.50,0.0,NIFTY22JANFUT,NIFTY,2022-01-27 15:30:30,17450.0,CE,2022-01-19 16:19:00,7.966319,0.128823,0.904365,195.503392

In [44]:
tmp = Calls[np.abs(Calls['delta'] - 0.5) <= 0.05].reset_index()
tmp = tmp[['date','opt_price','fut_price','volume_y','strike','days_to_expiry','IV','delta','vega']]
tmp

,date,opt_price,fut_price,volume_y,strike,days_to_expiry,IV,delta,vega
0,2021-12-31 09:15:00+05:30,307.30,17311.0,174100.0,17300.0,27.260764,0.132906,0.514517,339.407958
1,2021-12-31 09:15:00+05:30,254.40,17311.0,174100.0,17400.0,27.260764,0.130332,0.460889,341.164829
2,2021-12-31 09:15:00+05:30,337.50,17311.0,174100.0,17250.0,27.260764,0.134980,0.540507,338.272039
3,2021-12-31 09:15:00+05:30,275.55,17311.0,174100.0,17350.0,27.260764,0.129579,0.487438,340.909421
4,2021-12-31 09:16:00+05:30,316.85,17332.1,191750.0,17300.0,27.260069,0.132281,0.525659,339.801879
...,...,...,...,...,...,...,...,...,...
15285,2022-01-19 15:29:00+05:30,148.00,17975.5,38600.0,18000.0,8.001042,0.125094,0.480077,199.829629
15286,2022-01-19 15:30:00+05:30,148.00,17975.5,200.0,18000.0,8.000347,0.125100,0.480077,199.820957
15287,2022-01-19 15:30:00+05:30,175.30,17975.5,200.0,17950.0,8.000347,0.127059,0.529505,199.444574
15288,2022-01-19 16:19:00+05:30,148.00,17975.5,0.0,18000.0,7.966319,0.125367,0.480077,199.395556
15289,2022-01-19 16:19:00+05:30,175.30,17975.5,0.0,17950.0,7.966319,0.127330,0.529505,199.019975

In [45]:
train_set = pre_train_process(Calls,'2021-12-31 09:15:00+05:30',100,False,0.5)
train_set

             y        x1        x2
1   136.036135  0.503412  0.253424
2   161.443906  0.502790  0.252798
3   140.382259  0.477409  0.227920
4   131.838029  0.501339  0.251340
5   130.351215  0.502039  0.252043
6   135.021970  0.503343  0.253354
7   139.895675  0.479576  0.229993
8   113.676070  0.479051  0.229490
9   130.414473  0.503235  0.253246
10  160.962938  0.507495  0.257551
11  140.956689  0.486897  0.237068
12  113.479710  0.487509  0.237665
13  113.681305  0.490113  0.240210
14  130.929888  0.521766  0.272239
15  158.349353  0.522983  0.273511
16  148.766507  0.522442  0.272946
17  135.540843  0.497103  0.247111
18  111.955766  0.501583  0.251586
19  116.270521  0.475365  0.225972
20  132.170655  0.501996  0.252000
21  131.909262  0.500581  0.250582
22  133.562701  0.501150  0.251151
23  131.287384  0.499403  0.249404
24  132.530633  0.499969  0.249969
25  150.966141  0.524642  0.275249
26  136.972304  0.504971  0.254995
27  138.588688  0.475632  0.226226
28  129.015533  0.498889  0.248890
29  149.328918  0.523625  0.274183
30  133.567435  0.496387  0.246400
31  125.410725  0.523041  0.273572
32  131.149722  0.491512  0.241584
33  129.612728  0.523320  0.273864
34  152.766843  0.523830  0.274398
35  137.061251  0.499230  0.249230
36  134.515888  0.502289  0.252294
37  133.875821  0.502816  0.252824
38  138.665000  0.475750  0.226339
39  115.486100  0.475077  0.225698
40  131.427123  0.501596  0.251599
41  131.499127  0.501187  0.251188
42  131.293079  0.497862  0.247866
43  110.380782  0.501324  0.251326
44  131.591817  0.498549  0.248551
45  131.162722  0.496090  0.246106
46  128.295088  0.522888  0.273412
47  154.598131  0.524610  0.275216
48  134.434588  0.502659  0.252666
49  158.501918  0.501032  0.251033
50  133.340821  0.502683  0.252691
51  162.655649  0.502417  0.252423
52  139.255598  0.477570  0.228073
53  117.823983  0.479932  0.230335
54  133.447207  0.509932  0.260031
55  157.092979  0.507668  0.257726
56  138.372628  0.485879  0.236078
57  112.152208  0.482965  0.233256
58  113.137717  0.481208  0.231562